document.selection.Text = "r";
document.selection.Text = "e";
document.selection.Text = "p";
document.selection.Text = "e";
document.selection.Text = "a";
document.selection.Text = "t";
document.selection.Text = " ";
document.selection.Text = " ";
document.selection.Text = "1";
document.selection.NewLine(1);
document.selection.Text = "{";
document.selection.NewLine(1);
document.selection.Text = "\t";
document.selection.Text = "N";
document.selection.Text = "e";
document.selection.Text = "w";
document.selection.Text = "B";
document.selection.Text = "u";
document.selection.Text = "l";
document.selection.Text = "l";
document.selection.Text = "e";
document.selection.Text = "t";
document.selection.Text = "S";
document.selection.Text = "e";
document.selection.Text = "t";
document.selection.Text = " ";
document.selection.Text = "0";
document.selection.Text = " ";
document.selection.Text = "0";
document.selection.Text = " ";
document.selection.Text = "3";
document.selection.Text = " ";
document.selection.Text = "[";
document.selection.Text = "P";
document.selection.Text = "r";
document.selection.Text = "o";
document.selection.Text = "g";
document.selection.Text = "r";
document.selection.Text = "a";
document.selection.Text = "m";
document.selection.Text = "E";
document.selection.Text = "R";
document.selection.DeleteLeft(1);
document.selection.DeleteLeft(1);
document.selection.Text = "R";
document.selection.Text = "a";
document.selection.Text = "m";
document.selection.Text = "(";
document.selection.Text = "0";
document.selection.Text = ")";
document.selection.Text = "]";
document.selection.Text = " ";
document.selection.Text = "1";
document.selection.Text = "5";
document.selection.NewLine(1);
document.selection.Text = "+";
document.selection.Text = "+";
document.selection.Text = "+";
document.selection.Text = " ";
document.selection.Text = "3";
document.selection.Text = "0";
document.selection.NewLine(1);
document.selection.Text = "}";
document.selection.CharLeft(false, 1);
document.selection.DeleteLeft(1);
document.selection.CharLeft(false, 1);
document.selection.LineUp(false, 1);
document.selection.LineUp(false, 1);
document.selection.NewLine(1);
document.selection.Text = "\t";
document.selection.Text = "C";
document.selection.Text = "u";
document.selection.Text = "r";
document.selection.Text = "r";
document.selection.Text = "e";
document.selection.Text = "n";
document.selection.Text = "t";
document.selection.Text = "R";
document.selection.Text = "a";
document.selection.Text = "m";
document.selection.Text = " ";
document.selection.Text = "0";
